package org.brms.myproject;
global java.util.List value;
global java.util.List key;

rule "Had any bankruptcy"
when
Bankruptcy(hadBankruptcy=="yes")
then
        value.clear();
        key.clear();
        value.add("val:1");
        key.add("Display: Had a bankruptcy in the past five years");
end

rule "if no any bankruptcy"
when
Bankruptcy(hadBankruptcy!="yes")
then
        value.clear();
        key.clear();
        key.add("Display: Had no bankruptcy in the past five years");
end
