package org.brms.myproject;
global java.util.List value;
global java.util.List key;

rule "Time of Ownership"
    when
        Ownership((TimeOwnership<3)&&(TimeOwnership!=0))
    then
        value.clear();
        key.clear();
        value.add(1);
        key.add("Display: Have a prior address");
       // drools.setFocus("New purchase");
end

rule "Check whether new purchase"
//ruleflow-group "New purchase"
    when
        Ownership(TimeOwnership==0)
    then
        value.clear();
        key.clear();
        value.add(2);
        key.add("Display:The house is a new purchase");
end
	
rule "if Time of Ownership"
    when
        Ownership(TimeOwnership>=3)
    then
        value.clear();
        key.clear();
        value.add(0);
        key.add("Display:Don't have prior address");
end	   