package org.brms.myproject;
global java.util.List value;
global java.util.List key;

rule "Check if he has a trampoline"
when
additionalStructTrampoline(trampoline=="yes")
then
        value.clear();
        key.clear();
        value.add("val:1");
        key.add("Display: Has a trampoline at the house");
end

rule "Check if no trampoline"
when
additionalStructTrampoline(trampoline!="yes")
then
        value.clear();
        key.clear();
        key.add("Display: No trampoline at the house");
end
