package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ActivelyRepairing implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String activelyRepairing;

   public ActivelyRepairing()
   {
   }

   public java.lang.String getActivelyRepairing()
   {
      return this.activelyRepairing;
   }

   public void setActivelyRepairing(java.lang.String activelyRepairing)
   {
      this.activelyRepairing = activelyRepairing;
   }

   public ActivelyRepairing(java.lang.String activelyRepairing)
   {
      this.activelyRepairing = activelyRepairing;
   }

}