package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class additionalStructPool implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String pool;

   public additionalStructPool()
   {
   }

   public java.lang.String getPool()
   {
      return this.pool;
   }

   public void setPool(java.lang.String pool)
   {
      this.pool = pool;
   }

   public additionalStructPool(java.lang.String pool)
   {
      this.pool = pool;
   }

}