package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class additionalStructTrampoline implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String trampoline;

   public additionalStructTrampoline()
   {
   }

   public java.lang.String getTrampoline()
   {
      return this.trampoline;
   }

   public void setTrampoline(java.lang.String trampoline)
   {
      this.trampoline = trampoline;
   }

   public additionalStructTrampoline(java.lang.String trampoline)
   {
      this.trampoline = trampoline;
   }

}