package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class additionalStructGarage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String garage;

   public additionalStructGarage()
   {
   }

   public java.lang.String getGarage()
   {
      return this.garage;
   }

   public void setGarage(java.lang.String garage)
   {
      this.garage = garage;
   }

   public additionalStructGarage(java.lang.String garage)
   {
      this.garage = garage;
   }

}