package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alarm implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String alarm;

   public Alarm()
   {
   }

   public java.lang.String getAlarm()
   {
      return this.alarm;
   }

   public void setAlarm(java.lang.String alarm)
   {
      this.alarm = alarm;
   }

   public Alarm(java.lang.String alarm)
   {
      this.alarm = alarm;
   }

}