package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ASI implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String garageType;
   private java.lang.String secured_community;
   private java.lang.String roofMaterial;
   private java.lang.String dogBreed;
   private java.lang.Integer yearBuilt;

   private java.lang.String masonryFrame;

   private java.lang.Integer roofUpdateYear;

   private java.lang.String divingBoard;

   private java.lang.String poolSlide;

   private java.lang.Boolean trampoline;

   public ASI()
   {
   }

   public java.lang.String getGarageType()
   {
      return this.garageType;
   }

   public void setGarageType(java.lang.String garageType)
   {
      this.garageType = garageType;
   }

   public java.lang.String getSecured_community()
   {
      return this.secured_community;
   }

   public void setSecured_community(java.lang.String secured_community)
   {
      this.secured_community = secured_community;
   }

   public java.lang.String getRoofMaterial()
   {
      return this.roofMaterial;
   }

   public void setRoofMaterial(java.lang.String roofMaterial)
   {
      this.roofMaterial = roofMaterial;
   }

   public java.lang.String getDogBreed()
   {
      return this.dogBreed;
   }

   public void setDogBreed(java.lang.String dogBreed)
   {
      this.dogBreed = dogBreed;
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public java.lang.String getMasonryFrame()
   {
      return this.masonryFrame;
   }

   public void setMasonryFrame(java.lang.String masonryFrame)
   {
      this.masonryFrame = masonryFrame;
   }

   public java.lang.Integer getRoofUpdateYear()
   {
      return this.roofUpdateYear;
   }

   public void setRoofUpdateYear(java.lang.Integer roofUpdateYear)
   {
      this.roofUpdateYear = roofUpdateYear;
   }

   public java.lang.String getDivingBoard()
   {
      return this.divingBoard;
   }

   public void setDivingBoard(java.lang.String divingBoard)
   {
      this.divingBoard = divingBoard;
   }

   public java.lang.String getPoolSlide()
   {
      return this.poolSlide;
   }

   public void setPoolSlide(java.lang.String poolSlide)
   {
      this.poolSlide = poolSlide;
   }

   public java.lang.Boolean getTrampoline()
   {
      return this.trampoline;
   }

   public void setTrampoline(java.lang.Boolean trampoline)
   {
      this.trampoline = trampoline;
   }

   public ASI(java.lang.String garageType, java.lang.String secured_community,
         java.lang.String roofMaterial, java.lang.String dogBreed,
         java.lang.Integer yearBuilt, java.lang.String masonryFrame,
         java.lang.Integer roofUpdateYear, java.lang.String divingBoard,
         java.lang.String poolSlide, java.lang.Boolean trampoline)
   {
      this.garageType = garageType;
      this.secured_community = secured_community;
      this.roofMaterial = roofMaterial;
      this.dogBreed = dogBreed;
      this.yearBuilt = yearBuilt;
      this.masonryFrame = masonryFrame;
      this.roofUpdateYear = roofUpdateYear;
      this.divingBoard = divingBoard;
      this.poolSlide = poolSlide;
      this.trampoline = trampoline;
   }

}