package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bankruptcy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String hadBankruptcy;

   public Bankruptcy()
   {
   }

   public java.lang.String getHadBankruptcy()
   {
      return this.hadBankruptcy;
   }

   public void setHadBankruptcy(java.lang.String hadBankruptcy)
   {
      this.hadBankruptcy = hadBankruptcy;
   }

   public Bankruptcy(java.lang.String hadBankruptcy)
   {
      this.hadBankruptcy = hadBankruptcy;
   }

}