package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CurrentCoverage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String currentCoverage;

   public CurrentCoverage()
   {
   }

   public java.lang.String getCurrentCoverage()
   {
      return this.currentCoverage;
   }

   public void setCurrentCoverage(java.lang.String currentCoverage)
   {
      this.currentCoverage = currentCoverage;
   }

   public CurrentCoverage(java.lang.String currentCoverage)
   {
      this.currentCoverage = currentCoverage;
   }

}