package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerHome implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String customerInHome;

   public CustomerHome()
   {
   }

   public java.lang.String getCustomerInHome()
   {
      return this.customerInHome;
   }

   public void setCustomerInHome(java.lang.String customerInHome)
   {
      this.customerInHome = customerInHome;
   }

   public CustomerHome(java.lang.String customerInHome)
   {
      this.customerInHome = customerInHome;
   }

}