package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cypress implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer yearBuilt;

   private java.lang.String secured_community;

   private java.lang.Integer prior_Claims;

   private java.lang.String trampolinefence;

   private java.lang.String flatRoofPercent;

   private java.lang.String masonryFrame;

   private java.lang.String plumbingType;

   private java.lang.Integer plumbingUpdate;

   private java.lang.String liabilityClaims;

   private java.lang.Integer noPriorCoverage;

   private Boolean farmAnimals;

   private java.lang.String LLC;

   private java.lang.String divingBoard;

   private java.lang.String poolSlide;

   private java.lang.Boolean trampoline;

   private java.lang.Integer waterCoverage;

   private java.lang.String insuranceScore;

   private java.lang.String effectiveYearBuilt;

   private java.lang.String structureType;

   private java.lang.String dogBreed;

   private java.lang.String garageType;

   private java.lang.String roofMaterial;

   //public List <String> result = new ArrayList<String>();

   public java.lang.String result;

   private java.lang.Integer roofUpdateYear;

   private java.lang.Boolean alarm;

   private java.lang.String rentedStructure;

   public Cypress()
   {
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public java.lang.String getSecured_community()
   {
      return this.secured_community;
   }

   public void setSecured_community(java.lang.String secured_community)
   {
      this.secured_community = secured_community;
   }

   public java.lang.Integer getPrior_Claims()
   {
      return this.prior_Claims;
   }

   public void setPrior_Claims(java.lang.Integer prior_Claims)
   {
      this.prior_Claims = prior_Claims;
   }

   public java.lang.String getTrampolinefence()
   {
      return this.trampolinefence;
   }

   public void setTrampolinefence(java.lang.String trampolinefence)
   {
      this.trampolinefence = trampolinefence;
   }

   public java.lang.String getFlatRoofPercent()
   {
      return this.flatRoofPercent;
   }

   public void setFlatRoofPercent(java.lang.String flatRoofPercent)
   {
      this.flatRoofPercent = flatRoofPercent;
   }

   public java.lang.String getMasonryFrame()
   {
      return this.masonryFrame;
   }

   public void setMasonryFrame(java.lang.String masonryFrame)
   {
      this.masonryFrame = masonryFrame;
   }

   public java.lang.String getPlumbingType()
   {
      return this.plumbingType;
   }

   public void setPlumbingType(java.lang.String plumbingType)
   {
      this.plumbingType = plumbingType;
   }

   public java.lang.Integer getPlumbingUpdate()
   {
      return this.plumbingUpdate;
   }

   public void setPlumbingUpdate(java.lang.Integer plumbingUpdate)
   {
      this.plumbingUpdate = plumbingUpdate;
   }

   public java.lang.String getLiabilityClaims()
   {
      return this.liabilityClaims;
   }

   public void setLiabilityClaims(java.lang.String liabilityClaims)
   {
      this.liabilityClaims = liabilityClaims;
   }

   public java.lang.Integer getNoPriorCoverage()
   {
      return this.noPriorCoverage;
   }

   public void setNoPriorCoverage(java.lang.Integer noPriorCoverage)
   {
      this.noPriorCoverage = noPriorCoverage;
   }

   public java.lang.String getLLC()
   {
      return this.LLC;
   }

   public void setLLC(java.lang.String LLC)
   {
      this.LLC = LLC;
   }

   public java.lang.String getDivingBoard()
   {
      return this.divingBoard;
   }

   public void setDivingBoard(java.lang.String divingBoard)
   {
      this.divingBoard = divingBoard;
   }

   public java.lang.String getPoolSlide()
   {
      return this.poolSlide;
   }

   public void setPoolSlide(java.lang.String poolSlide)
   {
      this.poolSlide = poolSlide;
   }

   public java.lang.Boolean getTrampoline()
   {
      return this.trampoline;
   }

   public void setTrampoline(java.lang.Boolean trampoline)
   {
      this.trampoline = trampoline;
   }

   public java.lang.Integer getWaterCoverage()
   {
      return this.waterCoverage;
   }

   public void setWaterCoverage(java.lang.Integer waterCoverage)
   {
      this.waterCoverage = waterCoverage;
   }

   public java.lang.String getInsuranceScore()
   {
      return this.insuranceScore;
   }

   public void setInsuranceScore(java.lang.String insuranceScore)
   {
      this.insuranceScore = insuranceScore;
   }

   public java.lang.String getEffectiveYearBuilt()
   {
      return this.effectiveYearBuilt;
   }

   public void setEffectiveYearBuilt(java.lang.String effectiveYearBuilt)
   {
      this.effectiveYearBuilt = effectiveYearBuilt;
   }

   public java.lang.Boolean getFarmAnimals()
   {
      return this.farmAnimals;
   }

   public void setFarmAnimals(java.lang.Boolean farmAnimals)
   {
      this.farmAnimals = farmAnimals;
   }

   public java.lang.String getStructureType()
   {
      return this.structureType;
   }

   public void setStructureType(java.lang.String structureType)
   {
      this.structureType = structureType;
   }

   public java.lang.String getDogBreed()
   {
      return this.dogBreed;
   }

   public void setDogBreed(java.lang.String dogBreed)
   {
      this.dogBreed = dogBreed;
   }

   public java.lang.String getGarageType()
   {
      return this.garageType;
   }

   public void setGarageType(java.lang.String garageType)
   {
      this.garageType = garageType;
   }

   public java.lang.String getRoofMaterial()
   {
      return this.roofMaterial;
   }

   public void setRoofMaterial(java.lang.String roofMaterial)
   {
      this.roofMaterial = roofMaterial;
   }

   //public List<String> getResult()
   //{
   //  return this.result;
   //}

   public java.lang.String getResult()
   {
      return this.result;
   }

   public void setResult(java.lang.String result)
   {
      this.result = result;
   }

   public java.lang.Integer getRoofUpdateYear()
   {
      return this.roofUpdateYear;
   }

   public void setRoofUpdateYear(java.lang.Integer roofUpdateYear)
   {
      this.roofUpdateYear = roofUpdateYear;
   }

   public java.lang.Boolean getAlarm()
   {
      return this.alarm;
   }

   public void setAlarm(java.lang.Boolean alarm)
   {
      this.alarm = alarm;
   }

   public java.lang.String getRentedStructure()
   {
      return this.rentedStructure;
   }

   public void setRentedStructure(java.lang.String rentedStructure)
   {
      this.rentedStructure = rentedStructure;
   }

   public Cypress(java.lang.Integer yearBuilt, java.lang.String secured_community,
         java.lang.Integer prior_Claims, java.lang.String trampolinefence,
         java.lang.String flatRoofPercent, java.lang.String masonryFrame,
         java.lang.String plumbingType, java.lang.Integer plumbingUpdate,
         java.lang.String liabilityClaims, java.lang.Integer noPriorCoverage,
         java.lang.Boolean farmAnimals, java.lang.String LLC,
         java.lang.String divingBoard, java.lang.String poolSlide,
         java.lang.Boolean trampoline, java.lang.Integer waterCoverage,
         java.lang.String insuranceScore, java.lang.String effectiveYearBuilt,
         java.lang.String structureType, java.lang.String dogBreed,
         java.lang.String garageType, java.lang.String roofMaterial,
         java.lang.String result, java.lang.Integer roofUpdateYear,
         java.lang.Boolean alarm, java.lang.String rentedStructure)
   {
      this.yearBuilt = yearBuilt;
      this.secured_community = secured_community;
      this.prior_Claims = prior_Claims;
      this.trampolinefence = trampolinefence;
      this.flatRoofPercent = flatRoofPercent;
      this.masonryFrame = masonryFrame;
      this.plumbingType = plumbingType;
      this.plumbingUpdate = plumbingUpdate;
      this.liabilityClaims = liabilityClaims;
      this.noPriorCoverage = noPriorCoverage;
      this.farmAnimals = farmAnimals;
      this.LLC = LLC;
      this.divingBoard = divingBoard;
      this.poolSlide = poolSlide;
      this.trampoline = trampoline;
      this.waterCoverage = waterCoverage;
      this.insuranceScore = insuranceScore;
      this.effectiveYearBuilt = effectiveYearBuilt;
      this.structureType = structureType;
      this.dogBreed = dogBreed;
      this.garageType = garageType;
      this.roofMaterial = roofMaterial;
      this.result = result;
      this.roofUpdateYear = roofUpdateYear;
      this.alarm = alarm;
      this.rentedStructure = rentedStructure;
   }

}