package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dog implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String dog;

   public Dog()
   {
   }

   public java.lang.String getDog()
   {
      return this.dog;
   }

   public void setDog(java.lang.String dog)
   {
      this.dog = dog;
   }

   public Dog(java.lang.String dog)
   {
      this.dog = dog;
   }

}