package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FedNat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer yearBuilt;

   private java.lang.String secured_community;

   private java.lang.String trampolinefence;

   private java.lang.String flatRoofPercent;

   private java.lang.String masonryFrame;

   private java.lang.String divingBoard;

   private java.lang.String poolSlide;

   private java.lang.Boolean trampoline;

   private java.lang.String structureType;

   private java.lang.String dogBreed;

   private java.lang.String garageType;

   private java.lang.String roofMaterial;

   //public List <String> result = new ArrayList<String>();

   private java.lang.Integer roofUpdateYear;

   private java.lang.String rentedStructure;

   private java.lang.String alarm;

   private java.lang.String LLC;

   public FedNat()
   {
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public java.lang.String getSecured_community()
   {
      return this.secured_community;
   }

   public void setSecured_community(java.lang.String secured_community)
   {
      this.secured_community = secured_community;
   }

   public java.lang.String getTrampolinefence()
   {
      return this.trampolinefence;
   }

   public void setTrampolinefence(java.lang.String trampolinefence)
   {
      this.trampolinefence = trampolinefence;
   }

   public java.lang.String getFlatRoofPercent()
   {
      return this.flatRoofPercent;
   }

   public void setFlatRoofPercent(java.lang.String flatRoofPercent)
   {
      this.flatRoofPercent = flatRoofPercent;
   }

   public java.lang.String getMasonryFrame()
   {
      return this.masonryFrame;
   }

   public void setMasonryFrame(java.lang.String masonryFrame)
   {
      this.masonryFrame = masonryFrame;
   }

   public java.lang.String getDivingBoard()
   {
      return this.divingBoard;
   }

   public void setDivingBoard(java.lang.String divingBoard)
   {
      this.divingBoard = divingBoard;
   }

   public java.lang.String getPoolSlide()
   {
      return this.poolSlide;
   }

   public void setPoolSlide(java.lang.String poolSlide)
   {
      this.poolSlide = poolSlide;
   }

   public java.lang.Boolean getTrampoline()
   {
      return this.trampoline;
   }

   public void setTrampoline(java.lang.Boolean trampoline)
   {
      this.trampoline = trampoline;
   }

   public java.lang.String getStructureType()
   {
      return this.structureType;
   }

   public void setStructureType(java.lang.String structureType)
   {
      this.structureType = structureType;
   }

   public java.lang.String getDogBreed()
   {
      return this.dogBreed;
   }

   public void setDogBreed(java.lang.String dogBreed)
   {
      this.dogBreed = dogBreed;
   }

   public java.lang.String getGarageType()
   {
      return this.garageType;
   }

   public void setGarageType(java.lang.String garageType)
   {
      this.garageType = garageType;
   }

   public java.lang.String getRoofMaterial()
   {
      return this.roofMaterial;
   }

   public void setRoofMaterial(java.lang.String roofMaterial)
   {
      this.roofMaterial = roofMaterial;
   }

   //public List<String> getResult()
   //{
   //  return this.result;
   //}

   public java.lang.Integer getRoofUpdateYear()
   {
      return this.roofUpdateYear;
   }

   public void setRoofUpdateYear(java.lang.Integer roofUpdateYear)
   {
      this.roofUpdateYear = roofUpdateYear;
   }

   public java.lang.String getRentedStructure()
   {
      return this.rentedStructure;
   }

   public void setRentedStructure(java.lang.String rentedStructure)
   {
      this.rentedStructure = rentedStructure;
   }

   public java.lang.String getAlarm()
   {
      return this.alarm;
   }

   public void setAlarm(java.lang.String alarm)
   {
      this.alarm = alarm;
   }

   public java.lang.String getLLC()
   {
      return this.LLC;
   }

   public void setLLC(java.lang.String LLC)
   {
      this.LLC = LLC;
   }

   public FedNat(java.lang.Integer yearBuilt, java.lang.String secured_community,
         java.lang.String trampolinefence, java.lang.String flatRoofPercent,
         java.lang.String masonryFrame, java.lang.String divingBoard,
         java.lang.String poolSlide, java.lang.Boolean trampoline,
         java.lang.String structureType, java.lang.String dogBreed,
         java.lang.String garageType, java.lang.String roofMaterial,
         java.lang.Integer roofUpdateYear, java.lang.String rentedStructure,
         java.lang.String alarm, java.lang.String LLC)
   {
      this.yearBuilt = yearBuilt;
      this.secured_community = secured_community;
      this.trampolinefence = trampolinefence;
      this.flatRoofPercent = flatRoofPercent;
      this.masonryFrame = masonryFrame;
      this.divingBoard = divingBoard;
      this.poolSlide = poolSlide;
      this.trampoline = trampoline;
      this.structureType = structureType;
      this.dogBreed = dogBreed;
      this.garageType = garageType;
      this.roofMaterial = roofMaterial;
      this.roofUpdateYear = roofUpdateYear;
      this.rentedStructure = rentedStructure;
      this.alarm = alarm;
      this.LLC = LLC;
   }

}