package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FlatRoof implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String flatRoof;

   public FlatRoof()
   {
   }

   public java.lang.String getFlatRoof()
   {
      return this.flatRoof;
   }

   public void setFlatRoof(java.lang.String flatRoof)
   {
      this.flatRoof = flatRoof;
   }

   public FlatRoof(java.lang.String flatRoof)
   {
      this.flatRoof = flatRoof;
   }

}