package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Foreclosure implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String hadForeclosure;

   public Foreclosure()
   {
   }

   public java.lang.String getHadForeclosure()
   {
      return this.hadForeclosure;
   }

   public void setHadForeclosure(java.lang.String hadForeclosure)
   {
      this.hadForeclosure = hadForeclosure;
   }

   public Foreclosure(java.lang.String hadForeclosure)
   {
      this.hadForeclosure = hadForeclosure;
   }

}