package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Heating implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String heatingType;

   public Heating()
   {
   }

   public java.lang.String getHeatingType()
   {
      return this.heatingType;
   }

   public void setHeatingType(java.lang.String heatingType)
   {
      this.heatingType = heatingType;
   }

   public Heating(java.lang.String heatingType)
   {
      this.heatingType = heatingType;
   }

}