package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HomeBusiness implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String bussinessInHome;

   public HomeBusiness()
   {
   }

   public java.lang.String getBussinessInHome()
   {
      return this.bussinessInHome;
   }

   public void setBussinessInHome(java.lang.String bussinessInHome)
   {
      this.bussinessInHome = bussinessInHome;
   }

   public HomeBusiness(java.lang.String bussinessInHome)
   {
      this.bussinessInHome = bussinessInHome;
   }

}