package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InteriorReplumb implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String interiorReplumb;

   public InteriorReplumb()
   {
   }

   public java.lang.String getInteriorReplumb()
   {
      return this.interiorReplumb;
   }

   public void setInteriorReplumb(java.lang.String interiorReplumb)
   {
      this.interiorReplumb = interiorReplumb;
   }

   public InteriorReplumb(java.lang.String interiorReplumb)
   {
      this.interiorReplumb = interiorReplumb;
   }

}