package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewPurchase implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String fourPoint;

   private java.lang.String windMitigation;

   public NewPurchase()
   {
   }

   public java.lang.String getFourPoint()
   {
      return this.fourPoint;
   }

   public void setFourPoint(java.lang.String fourPoint)
   {
      this.fourPoint = fourPoint;
   }

   public java.lang.String getWindMitigation()
   {
      return this.windMitigation;
   }

   public void setWindMitigation(java.lang.String windMitigation)
   {
      this.windMitigation = windMitigation;
   }

   public NewPurchase(java.lang.String fourPoint, java.lang.String windMitigation)
   {
      this.fourPoint = fourPoint;
      this.windMitigation = windMitigation;
   }

}