package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class otherDetailsHorse implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String horse;

   public otherDetailsHorse()
   {
   }

   public java.lang.String getHorse()
   {
      return this.horse;
   }

   public void setHorse(java.lang.String horse)
   {
      this.horse = horse;
   }

   public otherDetailsHorse(java.lang.String horse)
   {
      this.horse = horse;
   }

}