package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class otherDetailsLivestock implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String livestock;

   public otherDetailsLivestock()
   {
   }

   public java.lang.String getLivestock()
   {
      return this.livestock;
   }

   public void setLivestock(java.lang.String livestock)
   {
      this.livestock = livestock;
   }

   public otherDetailsLivestock(java.lang.String livestock)
   {
      this.livestock = livestock;
   }

}