package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ownership implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer timeOwnership;

   private java.lang.String priorAddress;

   public Ownership()
   {
   }

   public java.lang.Integer getTimeOwnership()
   {
      return this.timeOwnership;
   }

   public void setTimeOwnership(java.lang.Integer timeOwnership)
   {
      this.timeOwnership = timeOwnership;
   }

   public java.lang.String getPriorAddress()
   {
      return this.priorAddress;
   }

   public void setPriorAddress(java.lang.String priorAddress)
   {
      this.priorAddress = priorAddress;
   }

   public Ownership(java.lang.Integer timeOwnership, java.lang.String priorAddress)
   {
      this.timeOwnership = timeOwnership;
      this.priorAddress = priorAddress;
   }

}