package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Plumbing implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String knowSystem;

   public Plumbing()
   {
   }

   public java.lang.String getKnowSystem()
   {
      return this.knowSystem;
   }

   public void setKnowSystem(java.lang.String knowSystem)
   {
      this.knowSystem = knowSystem;
   }

   public Plumbing(java.lang.String knowSystem)
   {
      this.knowSystem = knowSystem;
   }

}