package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Plumb implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String plumbingType;

   public Plumb()
   {
   }

   public java.lang.String getPlumbingType()
   {
      return this.plumbingType;
   }

   public void setPlumbingType(java.lang.String plumbingType)
   {
      this.plumbingType = plumbingType;
   }

   public Plumb(java.lang.String plumbingType)
   {
      this.plumbingType = plumbingType;
   }

}