package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer kitchenQual;
   private java.lang.Integer bathroomQual;
   private java.lang.Boolean pool;
   private java.lang.String screenedEnclosure;
   private java.lang.String roofMaterial;

   public Policy()
   {
   }

   public java.lang.Integer getKitchenQual()
   {
      return this.kitchenQual;
   }

   public void setKitchenQual(java.lang.Integer kitchenQual)
   {
      this.kitchenQual = kitchenQual;
   }

   public java.lang.Integer getBathroomQual()
   {
      return this.bathroomQual;
   }

   public void setBathroomQual(java.lang.Integer bathroomQual)
   {
      this.bathroomQual = bathroomQual;
   }

   public java.lang.Boolean getPool()
   {
      return this.pool;
   }

   public void setPool(java.lang.Boolean pool)
   {
      this.pool = pool;
   }

   public java.lang.String getScreenedEnclosure()
   {
      return this.screenedEnclosure;
   }

   public void setScreenedEnclosure(java.lang.String screenedEnclosure)
   {
      this.screenedEnclosure = screenedEnclosure;
   }

   public java.lang.String getRoofMaterial()
   {
      return this.roofMaterial;
   }

   public void setRoofMaterial(java.lang.String roofMaterial)
   {
      this.roofMaterial = roofMaterial;
   }

   public Policy(java.lang.Integer kitchenQual, java.lang.Integer bathroomQual,
         java.lang.Boolean pool, java.lang.String screenedEnclosure,
         java.lang.String roofMaterial)
   {
      this.kitchenQual = kitchenQual;
      this.bathroomQual = bathroomQual;
      this.pool = pool;
      this.screenedEnclosure = screenedEnclosure;
      this.roofMaterial = roofMaterial;
   }

}