package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PriorClaims implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer numberOfClaims;

   public PriorClaims()
   {
   }

   public java.lang.Integer getNumberOfClaims()
   {
      return this.numberOfClaims;
   }

   public void setNumberOfClaims(java.lang.Integer numberOfClaims)
   {
      this.numberOfClaims = numberOfClaims;
   }

   public PriorClaims(java.lang.Integer numberOfClaims)
   {
      this.numberOfClaims = numberOfClaims;
   }

}