package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RoofShape implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofShape;

   public RoofShape()
   {
   }

   public java.lang.String getRoofShape()
   {
      return this.roofShape;
   }

   public void setRoofShape(java.lang.String roofShape)
   {
      this.roofShape = roofShape;
   }

   public RoofShape(java.lang.String roofShape)
   {
      this.roofShape = roofShape;
   }

}