package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RoofReplacement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofReplacement;

   public RoofReplacement()
   {
   }

   public java.lang.String getRoofReplacement()
   {
      return this.roofReplacement;
   }

   public void setRoofReplacement(java.lang.String roofReplacement)
   {
      this.roofReplacement = roofReplacement;
   }

   public RoofReplacement(java.lang.String roofReplacement)
   {
      this.roofReplacement = roofReplacement;
   }

}