package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StructureType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String houseType;

   private java.lang.Integer stories;

   public StructureType()
   {
   }

   public java.lang.String getHouseType()
   {
      return this.houseType;
   }

   public void setHouseType(java.lang.String houseType)
   {
      this.houseType = houseType;
   }

   public java.lang.Integer getStories()
   {
      return this.stories;
   }

   public void setStories(java.lang.Integer stories)
   {
      this.stories = stories;
   }

   public StructureType(java.lang.String houseType, java.lang.Integer stories)
   {
      this.houseType = houseType;
      this.stories = stories;
   }

}