package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UnderMajorRenovation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String underRennovation;

   public UnderMajorRenovation()
   {
   }

   public java.lang.String getUnderRennovation()
   {
      return this.underRennovation;
   }

   public void setUnderRennovation(java.lang.String underRennovation)
   {
      this.underRennovation = underRennovation;
   }

   public UnderMajorRenovation(java.lang.String underRennovation)
   {
      this.underRennovation = underRennovation;
   }

}