package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UnrepairedDamage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String unrepairedDamage;

   public UnrepairedDamage()
   {
   }

   public java.lang.String getUnrepairedDamage()
   {
      return this.unrepairedDamage;
   }

   public void setUnrepairedDamage(java.lang.String unrepairedDamage)
   {
      this.unrepairedDamage = unrepairedDamage;
   }

   public UnrepairedDamage(java.lang.String unrepairedDamage)
   {
      this.unrepairedDamage = unrepairedDamage;
   }

}