package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WallConstruction implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String wallConstruction;

   public WallConstruction()
   {
   }

   public java.lang.String getWallConstruction()
   {
      return this.wallConstruction;
   }

   public void setWallConstruction(java.lang.String wallConstruction)
   {
      this.wallConstruction = wallConstruction;
   }

   public WallConstruction(java.lang.String wallConstruction)
   {
      this.wallConstruction = wallConstruction;
   }

}